# Revisits Per Trial

Experiment 1

```{r, include=F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path='e1_figures/')
knitr::opts_chunk$set(fig.width=7, fig.height=5)
knitr::opts_chunk$set(out.width="33%")
options(dplyr.summarise.inform=F)
```

```{r, include=F}
library(tidyverse)
library(ez)
library(gt)
```

## Raw data

This line reads in the dataset that results from collating the results files for each participant.

```{r get-raw-data-e1, echo=TRUE}
e1 <- readRDS("fgms_e1_allsubs.rds")
```

This renames the raw data but doesn't do any operations on it.

```{r raw, echo=TRUE}
# this tibble is one row for each tree visited saying whether it was a revisit or not
e1_revisits <-
  e1 %>%
  transmute(
    pp           = pid,
    condition    = R,
    stage        = as_factor(ifelse(trial<=5, "early", "late")),
    progress     = as_factor(trial),
    index        = index,
    tree         = tile,
    is_a_revisit = revisit
  )
```

## Aggregation 1: Trial counts

```{r agg1}
# First level of aggregation collapses over index and yields 
# a count for each trial: 
# each row is how many revisits they made on that trial
# THESE ARE TRIAL SUMS
TRIAL_SUMS <-
  e1_revisits %>% 
  group_by(pp, condition, stage, progress) %>% 
  summarise(nrevisits = sum(is_a_revisit), .groups = "drop_last")
```

## Aggregation 2: Participant means

```{r agg2}
# Second level of aggregation collapses over trials
# each row is the average number of revisits that participant 
# made in that combination of random/clumped and early/late
# THESE ARE PARTICIPANT MEANS
PARTICIPANT_MEANS <- 
  TRIAL_SUMS %>% 
  group_by(pp, condition, stage) %>% 
  summarise(meanrevisits=mean(nrevisits), .groups="drop_last")
```

## Descriptives

Condition descriptives

```{r CONDITION_DESCRIPTIVES}
# To generate mean and sd properly for each level of condition 
# (clumped/random), we first need data with one clumped score 
# for each participant and one random score for each 
# participant, averaging over early and late stages.
tempCond <- PARTICIPANT_MEANS %>% 
  group_by(pp,condition) %>% summarise(cmeans=mean(meanrevisits))
# Now we can ask for means and sd for clumped and random 
# that each pp contributed one value to
CONDITION_DESCRIPTIVES <- tempCond %>% 
  group_by(condition) %>% 
  summarise(mean=mean(cmeans), sd=sd(cmeans))
# issue the table
CONDITION_DESCRIPTIVES %>% 
  gt() %>% 
  tab_header("Revisits per trial descriptives") %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>% 
  gtsave("e1_tables/condition_means.png")
```

Stage descriptives 

```{r STAGE_DESCRIPTIVES}
# To generate mean and sd properly for each level of stage,
# we first need to collapse over condition (clumped/random)
# to get one score for each participant per level of stage
# (early/late)
tempStage <- PARTICIPANT_MEANS %>% 
  group_by(pp,stage) %>% 
  summarise(smeans=mean(meanrevisits))
# Now we can ask for means and sd per level of stage
STAGE_DESCRIPTIVES <- tempStage  %>% 
  group_by(stage) %>% 
  summarise(mean=mean(smeans),sd=sd(smeans))
# issue the table
STAGE_DESCRIPTIVES %>% 
  gt() %>% 
  tab_header("Revisits per trial descriptives") %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>% 
  gtsave("e1_tables/stage_means.png")
```

SxC Descriptives

```{r SxC_Descriptives}
# To get the 2 x 2 interaction means, yielding a 2x2 table with mean and sd
SxC_DESCRIPTIVES <- PARTICIPANT_MEANS %>% group_by(condition,stage) %>% summarise(mean=mean(meanrevisits),sd=sd(meanrevisits))
SxC_DESCRIPTIVES %>% 
  gt(rowname_col = "stage", groupname_col = "condition") %>% 
  tab_stubhead(label = "condition") %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>% 
  tab_header("Revisits per trial descriptives") %>% 
  gtsave("e1_tables/SxC_means.png")
```

## Plots

```{r progress-revisits, echo=F, out.width="50%", message=FALSE}
# Ten points along the x axis, each participant contributes one point per cell
ggplot(
  data=TRIAL_SUMS, 
  aes(x=progress, y=nrevisits, group=condition, pch=condition, fill=condition)
) +
  theme_bw()+
  theme(aspect.ratio = 1, panel.grid=element_blank())+
  scale_fill_manual(values=c("white", "black")) +
  scale_shape_manual(values=c(24,19)) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width=0.2, position=position_dodge(0.25)) +
  stat_summary(fun = mean, geom = "line", position=position_dodge(0.25)) + 
  stat_summary(fun = mean, geom = "point", size=3, position=position_dodge(0.25)) +
  geom_jitter(pch=1, width=0.1, alpha=0.4) 
ggsave("e1_plots/progress-revisits.png")
```

```{r stage-revisits, echo=F, out.width="50%", message=FALSE}
# Two points along the x axis, each participant contributes one point per cell
ggplot(
  data=PARTICIPANT_MEANS, 
  aes(x=stage, y=meanrevisits, group=condition, pch=condition, fill=condition)
) +
  theme_bw()+
  theme(aspect.ratio = 1, panel.grid=element_blank())+
  scale_fill_manual(values=c("white", "black")) +
  scale_shape_manual(values=c(24,19)) +
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", width=0.2, position=position_dodge(0.25)) +
  stat_summary(fun = mean, geom = "line", position=position_dodge(0.25)) + 
  stat_summary(fun = mean, geom = "point", size=3, position=position_dodge(0.25))
ggsave("e1_plots/stage-revisits.png")
```

## ANOVA

```{r, anova-revisits}
ez1 <- ezANOVA(
  data=PARTICIPANT_MEANS,
  wid=pp,
  within=.c(condition, stage),
  dv=meanrevisits
)
```

```{r anova-table-revisits, out.width="33%", echo=F}
ez1$ANOVA %>% 
  select(-ges) %>% 
  gt() %>% 
  tab_header(
    title="Revisits per trial",
    subtitle = "ANOVA table"
  ) %>% 
  fmt_number(
    columns = c("F"),
    rows=everything(),
    decimals=2
  )  %>% 
  fmt_number(
    columns = c("p"),
    rows=everything(),
    decimals=3
  ) %>% 
  cols_align(
    columns=`p<.05`,
    align="c"
  ) %>% 
  gtsave("e1_tables/anova-revisits-per-trial.png")
```

