# Trial Duration

Experiment 2

```{r e2_trialdur_setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.path='e2_figures/')
knitr::opts_chunk$set(fig.width=7, fig.height=5)
knitr::opts_chunk$set(out.width="33%")
options(dplyr.summarise.inform=F)
library(tidyverse)
library(ez)
library(gt)

e2 <- readRDS("fgms_e2_allsubs.rds")

e2_trialdur <-
  e2 %>%
  transmute(
    pp           = as_factor(participant),
    trial        = trial_number,
    resources    = factor(R, levels=c(".pat","dis"), labels=c("clumped", "random")),
    fading       = factor(V, levels=c(".fade","nofade"), labels=c("fade", "no_fade")),
    stage        = as_factor(ifelse(trial<=10, "early", "late")),
    index        = index,
    dur          = trialdur)

e2_trialdur_TRIAL_SUMS <- 
  e2_trialdur %>% 
  group_by(pp, resources, stage, fading, trial) %>% 
  summarise(trialdur=unique(dur))

e2_trialdur_PARTICIPANT_MEANS <-
  e2_trialdur_TRIAL_SUMS %>% 
  group_by(pp, resources, stage, fading) %>% 
  summarise(mean_trialdur_per_stage = mean(trialdur))

e2_trialdur_CONDITION_MEANS <-
  e2_trialdur_PARTICIPANT_MEANS %>% 
  group_by(resources, stage, fading) %>% 
  summarise(mean = mean(mean_trialdur_per_stage), sd = sd(mean_trialdur_per_stage)) 
e2_trialdur_CONDITION_MEANS_TABLE <- 
  e2_trialdur_CONDITION_MEANS %>% 
  ungroup() %>% 
  gt() %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>% 
  tab_header("Number of trees")
gtsave(data=e2_trialdur_CONDITION_MEANS_TABLE, filename="e2_tables/e2_trialdur_CONDITION_MEANS_TABLE.png")

e2_trialdur_RESOURCES_FADING_MEANS <-
  e2_trialdur_PARTICIPANT_MEANS %>% 
  group_by(resources, fading) %>% 
  summarise(mean = mean(mean_trialdur_per_stage), sd = sd(mean_trialdur_per_stage))
e2_trialdur_RESOURCES_FADING_MEANS_TABLE <-
  e2_trialdur_RESOURCES_FADING_MEANS %>% 
  ungroup() %>% 
  gt() %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>% 
  tab_header("Number of trees")
gtsave(data=e2_trialdur_RESOURCES_FADING_MEANS_TABLE, filename="e2_tables/e2_trialdur_RESOURCES_FADING_MEANS_TABLE.png")

e2_trialdur_RESOURCES_STAGE_MEANS <-
  e2_trialdur_PARTICIPANT_MEANS %>% 
  group_by(resources, stage) %>% 
  summarise(mean = mean(mean_trialdur_per_stage), sd = sd(mean_trialdur_per_stage))
e2_trialdur_RESOURCES_STAGE_MEANS_TABLE <-
  e2_trialdur_RESOURCES_STAGE_MEANS %>% 
  ungroup() %>% 
  gt() %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>% 
  tab_header("Number of trees")
gtsave(data=e2_trialdur_RESOURCES_STAGE_MEANS_TABLE, filename="e2_tables/e2_trialdur_RESOURCES_STAGE_MEANS_TABLE.png")

e2_trialdur_STAGE_FADING_MEANS <-
  e2_trialdur_PARTICIPANT_MEANS %>% 
  group_by(stage, fading) %>% 
  summarise(mean = mean(mean_trialdur_per_stage), sd = sd(mean_trialdur_per_stage))
e2_trialdur_STAGE_FADING_MEANS_TABLE <-
  e2_trialdur_STAGE_FADING_MEANS %>% 
  ungroup() %>%
  gt() %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>%
  tab_header("Number of trees")
gtsave(data=e2_trialdur_STAGE_FADING_MEANS_TABLE, "e2_tables/e2_trialdur_STAGE_FADING_MEANS_TABLE.png")
  
e2_trialdur_RESOURCES_MEANS <-
  e2_trialdur_PARTICIPANT_MEANS %>% 
  group_by(resources) %>%
  summarise(mean = mean(mean_trialdur_per_stage), sd = sd(mean_trialdur_per_stage))
e2_trialdur_RESOURCES_MEANS_TABLE <-
  e2_trialdur_RESOURCES_MEANS %>% 
  ungroup() %>% 
  gt() %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>%  
  tab_header("Number of trees")
gtsave(data=e2_trialdur_RESOURCES_MEANS_TABLE, "e2_tables/e2_trialdur_RESOURCES_MEANS_TABLE.png")

e2_trialdur_STAGE_MEANS <-
  e2_trialdur_PARTICIPANT_MEANS %>% 
  group_by(stage) %>% 
  summarise(mean = mean(mean_trialdur_per_stage), sd = sd(mean_trialdur_per_stage))
e2_trialdur_STAGE_MEANS_TABLE <-
  e2_trialdur_STAGE_MEANS %>% 
  ungroup() %>% 
  gt() %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>%  
  tab_header("Number of trees")
gtsave(data=e2_trialdur_STAGE_MEANS_TABLE, filename="e2_tables/e2_trialdur_STAGE_MEANS_TABLE.png")

e2_trialdur_FADING_MEANS <-
  e2_trialdur_PARTICIPANT_MEANS %>% 
  group_by(fading) %>% 
  summarise(mean = mean(mean_trialdur_per_stage), sd = sd(mean_trialdur_per_stage))
e2_trialdur_FADING_MEANS_TABLE <-
  e2_trialdur_FADING_MEANS %>% 
  ungroup() %>% 
  gt() %>% 
  fmt_number(columns = c("mean","sd"), decimals=2) %>%  
  tab_header("Number of trees")
gtsave(data=e2_trialdur_FADING_MEANS_TABLE, filename="e2_tables/e2_trialdur_FADING_MEANS_TABLE.png")

options(contrasts=c("contr.sum","contr.poly"))
e2_trialdur_ANOVA <- 
  ezANOVA(data=e2_trialdur_PARTICIPANT_MEANS,
          dv=mean_trialdur_per_stage,
          wid=pp,
          within=c(resources,stage),
          between=fading,
          type=3)

e2_trialdur_ANOVA_TABLE <-
  e2_trialdur_ANOVA$ANOVA %>% 
  select(-ges) %>% 
  gt() %>% 
  tab_header(
    title="Number of trees",
    subtitle = "ANOVA table"
  ) %>% 
  fmt_number(
    columns = c("F"),
    rows=everything(),
    decimals=2
  )  %>% 
  fmt_number(
    columns = c("p"),
    rows=everything(),
    decimals=3
  ) %>% 
  cols_align(
    columns=`p<.05`,
    align="c"
  ) %>% 
  gtsave("e2_tables/e2_trialdur_ANOVA.png")

# Ten points along the x axis, each participant contributes one point per cell
e2_trialdur_PLOT10 <-
  ggplot(
  data=e2_trialdur_TRIAL_SUMS, 
  aes(x=trial, y=trialdur, group=resources, pch=resources, fill=resources)
) +
  facet_wrap(~fading)+
  theme_bw()+
  theme(aspect.ratio = 1, panel.grid=element_blank())+
  scale_fill_manual(values=c("white", "black")) +
  scale_shape_manual(values=c(24,19)) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width=0.2, position=position_dodge(0.25)) +
  stat_summary(fun = mean, geom = "line", position=position_dodge(0.25)) + 
  stat_summary(fun = mean, geom = "point", size=3, position=position_dodge(0.25)) +
  geom_jitter(pch=1, width=0.1, alpha=0.4) 
ggsave("e2_plots/e2_trialdur_PLOT10.png")

# Two points along the x axis, each participant contributes one point per cell
e2_trialdur_PLOT2 <-
  ggplot(
  data=e2_trialdur_PARTICIPANT_MEANS, 
  aes(x=stage, y=mean_trialdur_per_stage, group=resources, pch=resources, fill=resources)
) +
  facet_wrap(~fading)+
  theme_bw()+
  theme(aspect.ratio = 1, panel.grid=element_blank())+
  scale_fill_manual(values=c("white", "black")) +
  scale_shape_manual(values=c(24,19)) +
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar", width=0.2, position=position_dodge(0.25)) +
  stat_summary(fun = mean, geom = "line", position=position_dodge(0.25)) + 
  stat_summary(fun = mean, geom = "point", size=3, position=position_dodge(0.25))
ggsave("e2_plots/e2_trialdur_PLOT2.png")
```

```{r}
e2_trialdur_ANOVA_TABLE
```

